<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AkunSeeder extends Seeder
{
    public function run(): void
    {
        $akun = [
            // ═══ AKTIVA LANCAR ═══
            [
                'kode_akun' => '1101',
                'nama_akun' => 'Kas',
                'pos_saldo' => 'debet',
                'pos_laporan' => 'neraca',
                'kategori_neraca' => 'aktiva_lancar',
                'kategori_laba_rugi' => null,
                'flag_transaksi_offline' => true,
                'flag_transaksi_online' => true,
                'flag_kas_offline' => true,
                'flag_kas_online' => true,
            ],
            [
                'kode_akun' => '1103',
                'nama_akun' => 'Piutang Usaha',
                'pos_saldo' => 'debet',
                'pos_laporan' => 'neraca',
                'kategori_neraca' => 'aktiva_lancar',
                'kategori_laba_rugi' => null,
                'flag_transaksi_offline' => false,
                'flag_transaksi_online' => false,
                'flag_kas_offline' => false,
                'flag_kas_online' => false,
            ],
            [
                'kode_akun' => '1104',
                'nama_akun' => 'Persediaan Barang Dagang',
                'pos_saldo' => 'debet',
                'pos_laporan' => 'neraca',
                'kategori_neraca' => 'aktiva_lancar',
                'kategori_laba_rugi' => null,
                'flag_transaksi_offline' => true,
                'flag_transaksi_online' => true,
                'flag_kas_offline' => false,
                'flag_kas_online' => false,
            ],
            [
                'kode_akun' => '1105',
                'nama_akun' => 'Perlengkapan',
                'pos_saldo' => 'debet',
                'pos_laporan' => 'neraca',
                'kategori_neraca' => 'aktiva_lancar',
                'kategori_laba_rugi' => null,
                'flag_transaksi_offline' => false,
                'flag_transaksi_online' => false,
                'flag_kas_offline' => false,
                'flag_kas_online' => false,
            ],

            // ═══ AKTIVA TETAP ═══
            [
                'kode_akun' => '1201',
                'nama_akun' => 'Peralatan Toko',
                'pos_saldo' => 'debet',
                'pos_laporan' => 'neraca',
                'kategori_neraca' => 'aktiva_tetap',
                'kategori_laba_rugi' => null,
                'flag_transaksi_offline' => false,
                'flag_transaksi_online' => false,
                'flag_kas_offline' => false,
                'flag_kas_online' => false,
            ],
            [
                'kode_akun' => '1202',
                'nama_akun' => 'Kendaraan',
                'pos_saldo' => 'debet',
                'pos_laporan' => 'neraca',
                'kategori_neraca' => 'aktiva_tetap',
                'kategori_laba_rugi' => null,
                'flag_transaksi_offline' => false,
                'flag_transaksi_online' => false,
                'flag_kas_offline' => false,
                'flag_kas_online' => false,
            ],

            // ═══ KEWAJIBAN ═══
            [
                'kode_akun' => '2101',
                'nama_akun' => 'Utang Usaha',
                'pos_saldo' => 'kredit',
                'pos_laporan' => 'neraca',
                'kategori_neraca' => 'kewajiban_lancar',
                'kategori_laba_rugi' => null,
                'flag_transaksi_offline' => false,
                'flag_transaksi_online' => false,
                'flag_kas_offline' => false,
                'flag_kas_online' => false,
            ],
            [
                'kode_akun' => '2102',
                'nama_akun' => 'Utang Bank',
                'pos_saldo' => 'kredit',
                'pos_laporan' => 'neraca',
                'kategori_neraca' => 'kewajiban_jangka_panjang',
                'kategori_laba_rugi' => null,
                'flag_transaksi_offline' => false,
                'flag_transaksi_online' => false,
                'flag_kas_offline' => false,
                'flag_kas_online' => false,
            ],

            // ═══ MODAL ═══
            [
                'kode_akun' => '3101',
                'nama_akun' => 'Modal Pemilik',
                'pos_saldo' => 'kredit',
                'pos_laporan' => 'neraca',
                'kategori_neraca' => 'modal',
                'kategori_laba_rugi' => null,
                'flag_transaksi_offline' => false,
                'flag_transaksi_online' => false,
                'flag_kas_offline' => false,
                'flag_kas_online' => false,
            ],
            [
                'kode_akun' => '3102',
                'nama_akun' => 'Prive Pemilik',
                'pos_saldo' => 'debet',
                'pos_laporan' => 'neraca',
                'kategori_neraca' => 'modal',
                'kategori_laba_rugi' => null,
                'flag_transaksi_offline' => false,
                'flag_transaksi_online' => false,
                'flag_kas_offline' => false,
                'flag_kas_online' => false,
            ],

            // ═══ PENDAPATAN (LABA RUGI) ═══
            [
                'kode_akun' => '4101',
                'nama_akun' => 'Pendapatan Penjualan',
                'pos_saldo' => 'kredit',
                'pos_laporan' => 'laba_rugi',
                'kategori_neraca' => null,
                'kategori_laba_rugi' => 'pendapatan',
                'flag_transaksi_offline' => true,
                'flag_transaksi_online' => true,
                'flag_kas_offline' => false,
                'flag_kas_online' => false,
            ],
            [
                'kode_akun' => '4102',
                'nama_akun' => 'Pendapatan Lain-lain',
                'pos_saldo' => 'kredit',
                'pos_laporan' => 'laba_rugi',
                'kategori_neraca' => null,
                'kategori_laba_rugi' => 'pendapatan_lain',
                'flag_transaksi_offline' => false,
                'flag_transaksi_online' => false,
                'flag_kas_offline' => false,
                'flag_kas_online' => false,
            ],

            // ═══ HPP (LABA RUGI) ═══
            [
                'kode_akun' => '5101',
                'nama_akun' => 'Harga Pokok Penjualan',
                'pos_saldo' => 'debet',
                'pos_laporan' => 'laba_rugi',
                'kategori_neraca' => null,
                'kategori_laba_rugi' => 'beban_pokok',
                'flag_transaksi_offline' => false,
                'flag_transaksi_online' => false,
                'flag_kas_offline' => false,
                'flag_kas_online' => false,
            ],

            // ═══ BEBAN OPERASIONAL (LABA RUGI) ═══
            [
                'kode_akun' => '6101',
                'nama_akun' => 'Beban Gaji Karyawan',
                'pos_saldo' => 'debet',
                'pos_laporan' => 'laba_rugi',
                'kategori_neraca' => null,
                'kategori_laba_rugi' => 'beban_operasional',
                'flag_transaksi_offline' => false,
                'flag_transaksi_online' => false,
                'flag_kas_offline' => true,
                'flag_kas_online' => true,
            ],
            [
                'kode_akun' => '6102',
                'nama_akun' => 'Beban Sewa',
                'pos_saldo' => 'debet',
                'pos_laporan' => 'laba_rugi',
                'kategori_neraca' => null,
                'kategori_laba_rugi' => 'beban_operasional',
                'flag_transaksi_offline' => false,
                'flag_transaksi_online' => false,
                'flag_kas_offline' => true,
                'flag_kas_online' => true,
            ],
            [
                'kode_akun' => '6103',
                'nama_akun' => 'Beban Listrik & Air',
                'pos_saldo' => 'debet',
                'pos_laporan' => 'laba_rugi',
                'kategori_neraca' => null,
                'kategori_laba_rugi' => 'beban_operasional',
                'flag_transaksi_offline' => false,
                'flag_transaksi_online' => false,
                'flag_kas_offline' => true,
                'flag_kas_online' => true,
            ],
            [
                'kode_akun' => '6104',
                'nama_akun' => 'Beban Transportasi',
                'pos_saldo' => 'debet',
                'pos_laporan' => 'laba_rugi',
                'kategori_neraca' => null,
                'kategori_laba_rugi' => 'beban_operasional',
                'flag_transaksi_offline' => false,
                'flag_transaksi_online' => false,
                'flag_kas_offline' => true,
                'flag_kas_online' => true,
            ],
            [
                'kode_akun' => '6105',
                'nama_akun' => 'Beban Telepon & Internet',
                'pos_saldo' => 'debet',
                'pos_laporan' => 'laba_rugi',
                'kategori_neraca' => null,
                'kategori_laba_rugi' => 'beban_operasional',
                'flag_transaksi_offline' => false,
                'flag_transaksi_online' => false,
                'flag_kas_offline' => true,
                'flag_kas_online' => true,
            ],
            [
                'kode_akun' => '6106',
                'nama_akun' => 'Beban Konsumsi',
                'pos_saldo' => 'debet',
                'pos_laporan' => 'laba_rugi',
                'kategori_neraca' => null,
                'kategori_laba_rugi' => 'beban_operasional',
                'flag_transaksi_offline' => false,
                'flag_transaksi_online' => false,
                'flag_kas_offline' => true,
                'flag_kas_online' => true,
            ],
            [
                'kode_akun' => '6107',
                'nama_akun' => 'Beban Lain-lain',
                'pos_saldo' => 'debet',
                'pos_laporan' => 'laba_rugi',
                'kategori_neraca' => null,
                'kategori_laba_rugi' => 'beban_operasional',
                'flag_transaksi_offline' => false,
                'flag_transaksi_online' => false,
                'flag_kas_offline' => true,
                'flag_kas_online' => true,
            ],
        ];

        foreach ($akun as $a) {
            DB::table('akun')->updateOrInsert(['kode_akun' => $a['kode_akun']], $a);
        }
    }
}
